CREATE TABLE IF NOT EXISTS gateway_payments (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  merchant_reference_id VARCHAR(64) NOT NULL,
  gateway VARCHAR(32) NOT NULL,
  purpose VARCHAR(32) NOT NULL DEFAULT 'deposit',
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  user_id BIGINT NOT NULL,
  user_type ENUM('live', 'strategy_provider', 'copy_follower') NOT NULL DEFAULT 'live',
  initiator_user_id BIGINT NULL,
  initiator_user_type ENUM('live', 'strategy_provider', 'copy_follower') NULL,
  requested_amount DECIMAL(18, 6) NOT NULL,
  requested_currency VARCHAR(10) NOT NULL DEFAULT 'USD',
  paid_amount DECIMAL(18, 6) NULL,
  paid_currency VARCHAR(10) NULL,
  settled_amount DECIMAL(18, 6) NULL,
  settled_currency VARCHAR(10) NOT NULL DEFAULT 'USD',
  credited_amount DECIMAL(18, 6) NULL,
  credited_currency VARCHAR(10) NOT NULL DEFAULT 'USD',
  exchange_rate DECIMAL(18, 8) NULL,
  fee_amount DECIMAL(18, 6) NULL,
  fee_currency VARCHAR(10) NULL,
  provider_reference_id VARCHAR(128) NULL,
  idempotency_key VARCHAR(128) NULL,
  transaction_id VARCHAR(30) NULL,
  provider_payload JSON NULL,
  metadata JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY idx_gateway_payments_merchant_reference_id (merchant_reference_id),
  KEY idx_gateway_payments_gateway (gateway),
  UNIQUE KEY idx_gateway_payments_gateway_provider_reference_id (gateway, provider_reference_id),
  KEY idx_gateway_payments_user_id (user_id),
  KEY idx_gateway_payments_user_type (user_type),
  KEY idx_gateway_payments_status (status),
  KEY idx_gateway_payments_idempotency_key (idempotency_key),
  UNIQUE KEY idx_gateway_payments_transaction_id (transaction_id),
  KEY idx_gateway_payments_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS gateway_payment_events (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  gateway_payment_id BIGINT NULL,
  gateway VARCHAR(32) NOT NULL,
  provider_event_id VARCHAR(128) NULL,
  event_type VARCHAR(64) NOT NULL,
  payload_hash VARCHAR(64) NULL,
  merchant_reference_id VARCHAR(64) NULL,
  provider_reference_id VARCHAR(128) NULL,
  processing_status VARCHAR(32) NOT NULL DEFAULT 'RECEIVED',
  processed_at DATETIME NULL,
  processing_error TEXT NULL,
  payload JSON NULL,
  metadata JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_gateway_payment_events_gateway_payment_id (gateway_payment_id),
  KEY idx_gateway_payment_events_gateway (gateway),
  UNIQUE KEY idx_gateway_payment_events_gateway_provider_event_id (gateway, provider_event_id),
  UNIQUE KEY idx_gateway_payment_events_gateway_payload_hash (gateway, payload_hash),
  KEY idx_gateway_payment_events_merchant_reference_id (merchant_reference_id),
  KEY idx_gateway_payment_events_provider_reference_id (provider_reference_id),
  KEY idx_gateway_payment_events_processing_status (processing_status),
  KEY idx_gateway_payment_events_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
